### ISSUE TITLE
Support for SHACL targets

### ISSUE THREAD

**Issue by jeswr** [hypermedia-app/shape-to-query#12]
It would be nice to have support for [SHACL Targets](https://www.w3.org/TR/shacl/#targets) in particular:
 - `sh:targetNode`: Substitute the `?resource1` variables with the target node (if there is one) or use `VALUES ( ?resource1 ) { ... }` if there are multiple.
 - `sh:targetClass`: In the where clause have `?resource1 a $targetClass .` if there is one or `?resource1 a ?targetClass . VALUES ( ?targetClass ) { ... }` if there are multiple.
 - `sh:targetObjectsOf`: In the where clause have `?s $targetObjectof ?resource1 .` if there is one or `?s ?targetObjectof ?resource1 . VALUES ( ?targetObjectof ) { ... }` if there are multiple.
 - `sh:targetSubjectsOf`: As above with `?resource1` as subject

**Comment by tpluscode** [comment]
I suppose that any combination of targets should be supported, and they would for a UNION, right?

**Comment by tpluscode** [comment]
I just deployed v0.4. 

Also, I started writing proper docs in bikeshed: https://shape-to-query.hypermedia.app/docs/.
