### ISSUE TITLE
Support for path of any complexity

### ISSUE THREAD

**Issue by tpluscode** [hypermedia-app/shape-to-query#8]
@jeswr

I was thinking about supporting complex paths. I previously implemented [clownface-shacl-path](https://npm.im/clownface-shacl-path) which does two things relevant to this library: 

1. generates equivalent SPARQL Property paths in the shortest form
2. converts a Sequence Path to a series of predicates, which can be easily reconstructed as multiple sparql patterns

The latter does not handle any other kind of SHACL Property Paths. The former looks like a better candidate for refactoring to get a series of patterns instead. Let's exercise some examples to see what we're dealing with. 
I will name all variables as `/\?seq(_\d)+_(s|p|o)/`

**Alternative path**

For the time being, I think your approach using `VALUES` makes sense

<table>
<tr>
<td> SHACL Path </td> 
<td>

```turtle
[ 
  sh:path [ 
    sh:alternativePath (
      schema:knows schema:spouse
    )
  ]
] .
```

</td>
</tr>
<td> SPARQL Path </td> 
<td>

```sparql
?seq_1_s schema:knows|schema:spouse ?seq_1_o
```

</td>
</tr>
<tr>
<td> Patterns </td> 
<td>

```sparql
?seq_1 ?seq_1_p ?seq_1 .
VALUES ?seq_1 {
  schema:knows schema:spouse
}
```

</td>
</tr>
</table>

**Inverse path + sequence**

This may seem easiest to handle by reversing the positions of `s` and `o` but I think it becomes confusing.

<table>
<tr>
<td> SHACL Path </td> 
<td>

```turtle
[ 
  sh:path (
    [ sh:inversePath schema:spouse ]
    [ sh:inversePath schema:knows ]
  )
] .
```

</td>
</tr>
<td> SPARQL Path </td> 
<td>

```sparql
?seq_1_s ^schema:spouse/^schema:knows ?seq_1_o
```

</td>
</tr>
<tr>
<td> Patterns </td> 
<td>

```sparql
?seq_1_s ^schema:spouse ?seq_1_o .
?seq_1_o ^schema:knows ?seq_2_o .
```

</td>
</tr>
</table>

**Sequence of two alternatives**

This is not unlike the above with `^prop` replaced with variable and values

<table>
<tr>
<td> SHACL Path </td> 
<td>

```turtle
[ 
  sh:path (
    [ sh:alternativePath ( schema:knows foaf:knows ) ]
    [ sh:alternativePath ( skos:prefLabel skos:altLabel ) ]
  )
] .
```

</td>
</tr>
<td> SPARQL Path </td> 
<td>

```sparql
?seq_1_s (schema:knows|foaf:knows)/(skos:prefLabel|skos:altLabel) ?seq_1_o
```

</td>
</tr>
<tr>
<td> Patterns </td> 
<td>

```sparql
?seq_1_s ?seq_1_p ?seq_1_o .
VALUES ?seq_1_p { schema:knows foaf:knows }
?seq_1_o ?seq_2_p ?seq_2_o .
VALUES ?seq_2_p { skos:prefLabel skos:altLabel }
```

</td>
</tr>
</table>

**Alternative of other paths**

I think this is where things start to become hairy.

<table>
<tr>
<td> SHACL Path </td> 
<td>

```turtle
[ 
  sh:path [
    sh:alternativePath (
      ( schema:knows schema:name )
      ( foaf:knows foaf:name )
    )
  )
] .
```

</td>
</tr>
<td> SPARQL Path </td> 
<td>

```sparql
?seq_1_s (schema:knows/schema:name)|(foaf:knows/foaf:name) ?seq_1_o
```

</td>
</tr>
<tr>
<td> Patterns </td> 
<td>

```sparql
{
  ?seq_1_s schema:knows ?seq_1_o .
  ?seq_1_o schema:name ?seq_2_o .
}
UNION
{
  ?seq_1_s foaf:knows ?seq_1_o .
  ?seq_1_o foaf:name ?seq_2_o .
}
```

</td>
</tr>
</table>

Is `UNION` the best way? If so, I think this is evidence that we may simply produce a `UNION` for any Alternative Path, such as that the example above becomes:

```sparql
{ ?seq_1_s schema:knows ?seq_1_o }
UNION
{ ?seq_1_s schema:spouse ?seq_1_o }
```

Any guesses whether SPARQL engines will like that?

**Comment by tpluscode** [comment]
Looking at the most complicated test case I have in `clownface-shacl-path` I begin to wonder if it is even possible to support all scenarios and keeps sanity

```turtle
sh:path (
  [ sh:zeroOrOnePath owl:sameAs ]
  [
    sh:alternativePath (
      [ sh:oneOrMorePath schema:name ]
      [ sh:zeroOrMorePath (owl:sameAs foaf:name) ]
      [ sh:inversePath ( ex:foo ex:bar ) ]
    )
  ]
)
```

And this becomes

```sparql
owl:sameAs?/(schema:knows+|(owl:sameAs/foaf:name)*|^(<http://example.com/foo>/<http://example.com/bar>))
```

**Comment by jeswr** [comment]
I think the biggest challenge here is the `(owl:sameAs/foaf:name)*` which I think is impossible without recursive sparql or path modifiers on variables.

**Comment by tpluscode** [comment]
I think you're right. For now maybe it's enough to only support `*OrMorePath` with a single predicate?

I have pushed the refactoring further in clownface-shacl-path. See the [`test.ts`](https://github.com/hypermedia-app/clownface-shacl-path/blob/visitor/test.ts#L15-L92) module which implements a new `PathVisitor`

Ultimately I found that in most cases paths boil down to `?start => ??? => ?end` and the necessary. I think, the new implementation also removes the necessity for this complicated variable naming scheme. Here's an example path

```turtle
[
  sh:path (
    [ sh:zeroOrOnePath owl.sameAs ]
    [
      sh:alternativePath [
        [ sh:oneOrMorePath schema.knows ]
        [ sh:zeroOrMorePath foaf.account ]
        [ sh:inversePath ( ex:foo ex:bar ) ]
      ]
    ]
] .
```

And query

```sparql
CONSTRUCT {
    ?node owl:sameAs ?node2 .
    ?node4 schema:knows ?node1 .
    ?node5 foaf:account ?node1 .
    ?node1 <http://example.com/foo> ?node6 .
    ?node6 <http://example.com/bar> ?node2 .
} WHERE {

    {
        BIND(?node as ?node2)
    } UNION {
        ?node owl:sameAs ?node2 .
    }
    {
        ?node2 schema:knows* ?node4 .
        ?node4 schema:knows ?node1 .
    } UNION {
        ?node2 foaf:account* ?node5 .
        ?node5 foaf:account ?node1 .
    } UNION {

        ?node1 <http://example.com/foo> ?node6 .
        ?node6 <http://example.com/bar> ?node2 .
    }
}
```
